/*
	ArrayOfWebworkSOAPClassesGlobalSet.h
	The interface definition of properties and methods for the ArrayOfWebworkSOAPClassesGlobalSet object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface ArrayOfWebworkSOAPClassesGlobalSet : SoapObject
{
	
}
		

	+ (ArrayOfWebworkSOAPClassesGlobalSet*) newWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
