/*
	ArrayOfWebworkSOAPClassesKey.h
	The interface definition of properties and methods for the ArrayOfWebworkSOAPClassesKey object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface ArrayOfWebworkSOAPClassesKey : SoapObject
{
	
}
		

	+ (ArrayOfWebworkSOAPClassesKey*) newWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
