/*
	WebworkSOAPClassesKey.h
	The interface definition of properties and methods for the WebworkSOAPClassesKey object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface WebworkSOAPClassesKey : SoapObject
{
	NSString* _user_id;
	NSString* _key_not_a_keyboard;
	NSString* _timestamp;
	
}
		
	@property (retain, nonatomic) NSString* user_id;
	@property (retain, nonatomic) NSString* key_not_a_keyboard;
	@property (retain, nonatomic) NSString* timestamp;

	+ (WebworkSOAPClassesKey*) newWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
