/*
	WebworkSOAPClassesPassword.h
	The interface definition of properties and methods for the WebworkSOAPClassesPassword object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface WebworkSOAPClassesPassword : SoapObject
{
	NSString* _user_id;
	NSString* _password;
	
}
		
	@property (retain, nonatomic) NSString* user_id;
	@property (retain, nonatomic) NSString* password;

	+ (WebworkSOAPClassesPassword*) newWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
