/*
	WebworkSOAPClassesPermission.h
	The interface definition of properties and methods for the WebworkSOAPClassesPermission object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface WebworkSOAPClassesPermission : SoapObject
{
	NSString* _user_id;
	NSString* _permission;
	
}
		
	@property (retain, nonatomic) NSString* user_id;
	@property (retain, nonatomic) NSString* permission;

	+ (WebworkSOAPClassesPermission*) newWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
