/*
	ArrayOfWebworkSOAPClassesPermission.h
	The interface definition of properties and methods for the ArrayOfWebworkSOAPClassesPermission object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface ArrayOfWebworkSOAPClassesPermission : SoapObject
{
	
}
		

	+ (ArrayOfWebworkSOAPClassesPermission*) newWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
