/*
	ArrayOfWebworkSOAPClassesPassword.h
	The interface definition of properties and methods for the ArrayOfWebworkSOAPClassesPassword object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface ArrayOfWebworkSOAPClassesPassword : SoapObject
{
	
}
		

	+ (ArrayOfWebworkSOAPClassesPassword*) newWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
