/*
	ArrayOfWebworkSOAPClassesUser.h
	The interface definition of properties and methods for the ArrayOfWebworkSOAPClassesUser object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface ArrayOfWebworkSOAPClassesUser : SoapObject
{
	
}
		

	+ (ArrayOfWebworkSOAPClassesUser*) newWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
