/*
	WebworkSOAPClassesUser.h
	The interface definition of properties and methods for the WebworkSOAPClassesUser object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface WebworkSOAPClassesUser : SoapObject
{
	NSString* _user_id;
	NSString* _first_name;
	NSString* _last_name;
	NSString* _email_address;
	NSString* _student_id;
	NSString* _status;
	NSString* _section;
	NSString* _recitation;
	NSString* _comment;
	
}
		
	@property (retain, nonatomic) NSString* user_id;
	@property (retain, nonatomic) NSString* first_name;
	@property (retain, nonatomic) NSString* last_name;
	@property (retain, nonatomic) NSString* email_address;
	@property (retain, nonatomic) NSString* student_id;
	@property (retain, nonatomic) NSString* status;
	@property (retain, nonatomic) NSString* section;
	@property (retain, nonatomic) NSString* recitation;
	@property (retain, nonatomic) NSString* comment;

	+ (WebworkSOAPClassesUser*) newWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
