/*
	WebworkSOAPHandlerService.h
	The interface definition of classes and methods for the WebworkSOAPHandlerService web service.
	Generated by SudzC.com
*/
				
#import "Soap.h"
	
/* Add class references */
				
#import "ArrayOfString.h"
#import "ArrayOfWebworkSOAPClassesKey.h"
#import "ArrayOfWebworkSOAPClassesUserSet.h"
#import "ArrayOfWebworkSOAPClassesUserProblem.h"
#import "ArrayOfWebworkSOAPClassesGlobalSet.h"
#import "ArrayOfWebworkSOAPClassesPassword.h"
#import "ArrayOfWebworkSOAPClassesUser.h"
#import "ArrayOfWebworkSOAPClassesGlobalProblem.h"
#import "ArrayOfWebworkSOAPClassesPermission.h"
#import "WebworkSOAPClassesUserProblem.h"
#import "WebworkSOAPClassesGlobalSet.h"
#import "WebworkSOAPClassesUserSet.h"
#import "WebworkSOAPClassesPassword.h"
#import "WebworkSOAPClassesPermission.h"
#import "WebworkSOAPClassesKey.h"
#import "WebworkSOAPClassesGlobalProblem.h"
#import "WebworkSOAPClassesUser.h"

/* Interface for the service */
				
@interface WebworkSOAPHandlerService : SoapService
		
	/* Returns NSString*.  */
	- (SoapRequest*) hello: (id <SoapDelegate>) handler;
	- (SoapRequest*) hello: (id) target action: (SEL) action;

	/* Returns ArrayOfString*.  */
	- (SoapRequest*) list_courses: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey;
	- (SoapRequest*) list_courses: (id) target action: (SEL) action authenKey: (NSString*) authenKey;

	/* Returns NSString*.  */
	- (SoapRequest*) login_user: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID;
	- (SoapRequest*) login_user: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID;

	/* Returns NSString*.  */
	- (SoapRequest*) assign_set_to_user: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID setID: (NSString*) setID;
	- (SoapRequest*) assign_set_to_user: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID setID: (NSString*) setID;

	/* Returns ArrayOfString*.  */
	- (SoapRequest*) grade_users_sets: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName userIDs: (ArrayOfString*) userIDs setID: (NSString*) setID;
	- (SoapRequest*) grade_users_sets: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName userIDs: (ArrayOfString*) userIDs setID: (NSString*) setID;

	/* Returns WebworkSOAPClassesGlobalSet*.  */
	- (SoapRequest*) get_set_data: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName setID: (NSString*) setID;
	- (SoapRequest*) get_set_data: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName setID: (NSString*) setID;

	/* Returns NSString*.  */
	- (SoapRequest*) add_password: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesPassword*) record;
	- (SoapRequest*) add_password: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesPassword*) record;

	/* Returns NSString*.  */
	- (SoapRequest*) put_password: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesPassword*) record;
	- (SoapRequest*) put_password: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesPassword*) record;

	/* Returns ArrayOfString*.  */
	- (SoapRequest*) list_password: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName;
	- (SoapRequest*) list_password: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName;

	/* Returns ArrayOfWebworkSOAPClassesPassword*.  */
	- (SoapRequest*) get_passwords: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName userIDs: (ArrayOfString*) userIDs;
	- (SoapRequest*) get_passwords: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName userIDs: (ArrayOfString*) userIDs;

	/* Returns WebworkSOAPClassesPassword*.  */
	- (SoapRequest*) get_password: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID;
	- (SoapRequest*) get_password: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID;

	/* Returns NSString*.  */
	- (SoapRequest*) add_permission: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesPermission*) record;
	- (SoapRequest*) add_permission: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesPermission*) record;

	/* Returns NSString*.  */
	- (SoapRequest*) put_permission: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesPermission*) record;
	- (SoapRequest*) put_permission: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesPermission*) record;

	/* Returns ArrayOfString*.  */
	- (SoapRequest*) list_permissions: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName;
	- (SoapRequest*) list_permissions: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName;

	/* Returns ArrayOfWebworkSOAPClassesPermission*.  */
	- (SoapRequest*) get_permissions: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName userIDs: (ArrayOfString*) userIDs;
	- (SoapRequest*) get_permissions: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName userIDs: (ArrayOfString*) userIDs;

	/* Returns WebworkSOAPClassesPermission*.  */
	- (SoapRequest*) get_permission: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID;
	- (SoapRequest*) get_permission: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID;

	/* Returns NSString*.  */
	- (SoapRequest*) add_key: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesKey*) record;
	- (SoapRequest*) add_key: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesKey*) record;

	/* Returns NSString*.  */
	- (SoapRequest*) put_key: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesKey*) record;
	- (SoapRequest*) put_key: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesKey*) record;

	/* Returns ArrayOfString*.  */
	- (SoapRequest*) list_keys: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName;
	- (SoapRequest*) list_keys: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName;

	/* Returns ArrayOfWebworkSOAPClassesKey*.  */
	- (SoapRequest*) get_keys: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName userIDs: (ArrayOfString*) userIDs;
	- (SoapRequest*) get_keys: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName userIDs: (ArrayOfString*) userIDs;

	/* Returns WebworkSOAPClassesKey*.  */
	- (SoapRequest*) get_key: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID;
	- (SoapRequest*) get_key: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID;

	/* Returns NSString*.  */
	- (SoapRequest*) add_user: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesUser*) record;
	- (SoapRequest*) add_user: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesUser*) record;

	/* Returns NSString*.  */
	- (SoapRequest*) put_user: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesUser*) record;
	- (SoapRequest*) put_user: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesUser*) record;

	/* Returns ArrayOfString*.  */
	- (SoapRequest*) list_users: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName;
	- (SoapRequest*) list_users: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName;

	/* Returns WebworkSOAPClassesUser*.  */
	- (SoapRequest*) get_user: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID;
	- (SoapRequest*) get_user: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID;

	/* Returns ArrayOfWebworkSOAPClassesUser*.  */
	- (SoapRequest*) get_users: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName userIDs: (ArrayOfString*) userIDs;
	- (SoapRequest*) get_users: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName userIDs: (ArrayOfString*) userIDs;

	/* Returns NSString*.  */
	- (SoapRequest*) delete_user: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID;
	- (SoapRequest*) delete_user: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID;

	/* Returns NSString*.  */
	- (SoapRequest*) add_global_set: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesGlobalSet*) record;
	- (SoapRequest*) add_global_set: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesGlobalSet*) record;

	/* Returns NSString*.  */
	- (SoapRequest*) put_global_set: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesGlobalSet*) record;
	- (SoapRequest*) put_global_set: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesGlobalSet*) record;

	/* Returns ArrayOfString*.  */
	- (SoapRequest*) list_global_sets: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName;
	- (SoapRequest*) list_global_sets: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName;

	/* Returns ArrayOfWebworkSOAPClassesGlobalSet*.  */
	- (SoapRequest*) get_all_global_sets: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName;
	- (SoapRequest*) get_all_global_sets: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName;

	/* Returns ArrayOfWebworkSOAPClassesGlobalSet*.  */
	- (SoapRequest*) get_global_sets: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName setIDs: (ArrayOfString*) setIDs;
	- (SoapRequest*) get_global_sets: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName setIDs: (ArrayOfString*) setIDs;

	/* Returns WebworkSOAPClassesGlobalSet*.  */
	- (SoapRequest*) get_global_set: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName setID: (NSString*) setID;
	- (SoapRequest*) get_global_set: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName setID: (NSString*) setID;

	/* Returns NSString*.  */
	- (SoapRequest*) delete_global_set: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName setID: (NSString*) setID;
	- (SoapRequest*) delete_global_set: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName setID: (NSString*) setID;

	/* Returns NSString*.  */
	- (SoapRequest*) add_global_problem: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesGlobalProblem*) record;
	- (SoapRequest*) add_global_problem: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesGlobalProblem*) record;

	/* Returns NSString*.  */
	- (SoapRequest*) put_global_problem: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesGlobalProblem*) record;
	- (SoapRequest*) put_global_problem: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesGlobalProblem*) record;

	/* Returns ArrayOfString*.  */
	- (SoapRequest*) list_global_problems: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName setID: (NSString*) setID;
	- (SoapRequest*) list_global_problems: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName setID: (NSString*) setID;

	/* Returns ArrayOfWebworkSOAPClassesGlobalProblem*.  */
	- (SoapRequest*) get_all_global_problems: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName setID: (NSString*) setID;
	- (SoapRequest*) get_all_global_problems: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName setID: (NSString*) setID;

	/* Returns WebworkSOAPClassesGlobalProblem*.  */
	- (SoapRequest*) get_global_problem: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName setID: (NSString*) setID problemID: (NSString*) problemID;
	- (SoapRequest*) get_global_problem: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName setID: (NSString*) setID problemID: (NSString*) problemID;

	/* Returns NSString*.  */
	- (SoapRequest*) delete_global_problem: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName setID: (NSString*) setID problemID: (NSString*) problemID;
	- (SoapRequest*) delete_global_problem: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName setID: (NSString*) setID problemID: (NSString*) problemID;

	/* Returns NSString*.  */
	- (SoapRequest*) add_user_problem: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesUserProblem*) record;
	- (SoapRequest*) add_user_problem: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesUserProblem*) record;

	/* Returns NSString*.  */
	- (SoapRequest*) put_user_problem: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesUserProblem*) record;
	- (SoapRequest*) put_user_problem: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesUserProblem*) record;

	/* Returns ArrayOfString*.  */
	- (SoapRequest*) list_user_problems: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID setID: (NSString*) setID;
	- (SoapRequest*) list_user_problems: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID setID: (NSString*) setID;

	/* Returns ArrayOfWebworkSOAPClassesUserProblem*.  */
	- (SoapRequest*) get_all_user_problems: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID setID: (NSString*) setID;
	- (SoapRequest*) get_all_user_problems: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID setID: (NSString*) setID;

	/* Returns ArrayOfWebworkSOAPClassesUserProblem*.  */
	- (SoapRequest*) get_user_problems: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName userProblemIDs: (ArrayOfString*) userProblemIDs;
	- (SoapRequest*) get_user_problems: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName userProblemIDs: (ArrayOfString*) userProblemIDs;

	/* Returns WebworkSOAPClassesUserProblem*.  */
	- (SoapRequest*) get_user_problem: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID setID: (NSString*) setID problemID: (NSString*) problemID;
	- (SoapRequest*) get_user_problem: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID setID: (NSString*) setID problemID: (NSString*) problemID;

	/* Returns NSString*.  */
	- (SoapRequest*) delete_user_problem: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID setID: (NSString*) setID problemID: (NSString*) problemID;
	- (SoapRequest*) delete_user_problem: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID setID: (NSString*) setID problemID: (NSString*) problemID;

	/* Returns NSString*.  */
	- (SoapRequest*) add_user_set: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesUserSet*) record;
	- (SoapRequest*) add_user_set: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesUserSet*) record;

	/* Returns NSString*.  */
	- (SoapRequest*) put_user_set: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesUserSet*) record;
	- (SoapRequest*) put_user_set: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName record: (WebworkSOAPClassesUserSet*) record;

	/* Returns ArrayOfString*.  */
	- (SoapRequest*) list_user_sets: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID;
	- (SoapRequest*) list_user_sets: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID;

	/* Returns ArrayOfWebworkSOAPClassesUserSet*.  */
	- (SoapRequest*) get_all_user_sets: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName;
	- (SoapRequest*) get_all_user_sets: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName;

	/* Returns ArrayOfWebworkSOAPClassesUserSet*.  */
	- (SoapRequest*) get_user_sets: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName userSetIDs: (NSString*) userSetIDs;
	- (SoapRequest*) get_user_sets: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName userSetIDs: (NSString*) userSetIDs;

	/* Returns WebworkSOAPClassesUserSet*.  */
	- (SoapRequest*) get_user_set: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID setID: (NSString*) setID;
	- (SoapRequest*) get_user_set: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID setID: (NSString*) setID;

	/* Returns NSString*.  */
	- (SoapRequest*) delete_user_set: (id <SoapDelegate>) handler authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID setID: (NSString*) setID;
	- (SoapRequest*) delete_user_set: (id) target action: (SEL) action authenKey: (NSString*) authenKey courseName: (NSString*) courseName userID: (NSString*) userID setID: (NSString*) setID;

		
	+ (WebworkSOAPHandlerService*) service;
	+ (WebworkSOAPHandlerService*) serviceWithUsername: (NSString*) username andPassword: (NSString*) password;
@end
	