/*
	WebworkSOAPClassesKey.h
	The implementation of properties and methods for the WebworkSOAPClassesKey object.
	Generated by SudzC.com
*/
#import "WebworkSOAPClassesKey.h"

@implementation WebworkSOAPClassesKey
	@synthesize user_id = _user_id;
	@synthesize key_not_a_keyboard = _key_not_a_keyboard;
	@synthesize timestamp = _timestamp;

	- (id) init
	{
		if(self = [super init])
		{
			self.user_id = nil;
			self.key_not_a_keyboard = nil;
			self.timestamp = nil;

		}
		return self;
	}

	+ (WebworkSOAPClassesKey*) newWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return (WebworkSOAPClassesKey*)[[[WebworkSOAPClassesKey alloc] initWithNode: node] autorelease];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.user_id = [Soap getNodeValue: node withName: @"user_id"];
			self.key_not_a_keyboard = [Soap getNodeValue: node withName: @"key_not_a_keyboard"];
			self.timestamp = [Soap getNodeValue: node withName: @"timestamp"];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"WebworkSOAPClassesKey"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.user_id != nil) [s appendFormat: @"<user_id>%@</user_id>", [[self.user_id stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.key_not_a_keyboard != nil) [s appendFormat: @"<key_not_a_keyboard>%@</key_not_a_keyboard>", [[self.key_not_a_keyboard stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.timestamp != nil) [s appendFormat: @"<timestamp>%@</timestamp>", [[self.timestamp stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[WebworkSOAPClassesKey class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}
	
	- (void) dealloc
	{
		if(self.user_id != nil) { [self.user_id release]; }
		if(self.key_not_a_keyboard != nil) { [self.key_not_a_keyboard release]; }
		if(self.timestamp != nil) { [self.timestamp release]; }
		[super dealloc];
	}

@end
