/*
	WebworkSOAPClassesGlobalSet.h
	The interface definition of properties and methods for the WebworkSOAPClassesGlobalSet object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface WebworkSOAPClassesGlobalSet : SoapObject
{
	NSString* _set_id;
	NSString* _set_header;
	NSString* _hardcopy_header;
	NSString* _open_date;
	NSString* _due_date;
	NSString* _answer_date;
	NSString* _visible;
	NSString* _enable_reduced_scoring;
	NSString* _assignment_type;
	NSString* _attempts_per_version;
	NSString* _time_interval;
	NSString* _versions_per_interval;
	NSString* _version_time_limit;
	NSString* _version_creation_time;
	NSString* _problem_randorder;
	NSString* _version_last_attempt_time;
	NSString* _problems_per_page;
	
}
		
	@property (retain, nonatomic) NSString* set_id;
	@property (retain, nonatomic) NSString* set_header;
	@property (retain, nonatomic) NSString* hardcopy_header;
	@property (retain, nonatomic) NSString* open_date;
	@property (retain, nonatomic) NSString* due_date;
	@property (retain, nonatomic) NSString* answer_date;
	@property (retain, nonatomic) NSString* visible;
	@property (retain, nonatomic) NSString* enable_reduced_scoring;
	@property (retain, nonatomic) NSString* assignment_type;
	@property (retain, nonatomic) NSString* attempts_per_version;
	@property (retain, nonatomic) NSString* time_interval;
	@property (retain, nonatomic) NSString* versions_per_interval;
	@property (retain, nonatomic) NSString* version_time_limit;
	@property (retain, nonatomic) NSString* version_creation_time;
	@property (retain, nonatomic) NSString* problem_randorder;
	@property (retain, nonatomic) NSString* version_last_attempt_time;
	@property (retain, nonatomic) NSString* problems_per_page;

	+ (WebworkSOAPClassesGlobalSet*) newWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
